{
	"version": 1699528508,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/character-sheet0.png",
		"images/ground-sheet0.png",
		"images/anaconda-sheet0.png",
		"images/bulletanaconda-sheet0.png",
		"images/cleaner-sheet0.png",
		"images/lifeline-sheet0.png",
		"images/bulletcharcter-sheet0.png",
		"images/rocketcharacter-sheet0.png",
		"images/jaguar-sheet0.png",
		"images/bulletmegalania-sheet0.png",
		"images/megalania-sheet0.png",
		"images/rocketmegalania-sheet0.png",
		"images/hornet-sheet0.png",
		"images/powerup-sheet0.png",
		"images/megalaniaexplosion-sheet0.png",
		"images/megalaniaexplosion-sheet1.png",
		"images/charachterexplosion-sheet0.png",
		"images/charachterexplosion-sheet1.png",
		"images/hornetexplosion-sheet0.png",
		"images/hornetexplosion-sheet1.png",
		"images/lifepower-sheet0.png",
		"images/charchterrocketexplosion-sheet0.png",
		"images/charchterrocketexplosion-sheet1.png",
		"images/launch_bt-sheet0.png",
		"images/pause_bt-sheet0.png",
		"images/toucharea-sheet0.png",
		"images/bstart-sheet0.png",
		"images/menu_bg-sheet0.png",
		"images/audio_bt-sheet0.png",
		"images/audio_bt-sheet1.png",
		"images/play_pause_bt-sheet0.png",
		"images/play_pause_bt-sheet1.png",
		"images/game_bg-sheet0.png",
		"images/home_bt-sheet0.png",
		"media/airshot3.m4a",
		"media/airshot3.ogg",
		"media/ricochet 1.m4a",
		"media/ricochet 1.ogg",
		"media/explosion 5.m4a",
		"media/explosion 5.ogg",
		"media/airshot1.m4a",
		"media/airshot1.ogg",
		"media/explosion 4.m4a",
		"media/explosion 4.ogg",
		"media/the rush_2.m4a",
		"media/the rush_2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}